### PR TITLE
handle groups

### LINKED ISSUE #9: Update variable inside group
Created PR for this:
https://github.com/idling-mind/pptx_renderer/pull/8

Updated main function to break out handlers (`handle_text_frame()` and `handle_table()`) and the ability to recurse into a group of shapes.

### PR DESCRIPTION
**Pull request by mr-menno**
created function `handle_shapes` which handles the shapes returned from a slide.
created function `handle_text_frame` and `handle_table` to handle the respective shapes (no other code changes)

`handle_shapes` sends the shape to the appropriate handler, or back to `handle_shapes` if it's a group of shapes.

### CODE REVIEW

**Comment by idling-mind** [comment]
Hi, Thanks for the contribution. Please fix the error in the pipeline. Seems like you have not defined the variable `GROUP` used to check if a shape is a group or not.

**Comment by mr-menno** [comment]
I’ve replaced GROUP with the correct import from the Python-pptx library.

**Comment by mr-menno** [comment]
@idling-mind could you rerun the pipelines when you get a chance?

**Comment by mr-menno** [comment]
@idling-mind thoughts about including this into the library?

**Comment by idling-mind** [comment]
hi, Looks good to me!

**Pull request merged**
